- hosts: all
  become: true
  tasks:

  - name: Change hostnames
    shell: "hostnamectl set-hostname {{ hostvars[inventory_hostname]['private_dns_name'] }}"

  - name: Swap off
    shell: |
      free -m
      swapoff -a && sed -i '/ swap / s/^/#/' /etc/fstab

  - name: Enable the nodes to see bridged traffic
    shell: |
      cat << EOF | sudo tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward                 = 1
      EOF
      sysctl --system

  - name: Update apt-get
    shell: apt-get update -y

  - name: Upgrade packages
    shell: apt-get upgrade -y

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https  
      - curl
      - ca-certificates

  - name: Add Kubernetes repository key and source list
    shell: |
      sudo mkdir -p /etc/apt/keyrings
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

  - name: Update apt-get after adding Kubernetes repo
    shell: apt-get update -y

  - name: Install Kubernetes and Docker packages
    apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
        - kubernetes-cni
        - docker.io
      state: present

  - name: Hold Kubernetes packages
    shell: apt-mark hold kubelet kubeadm kubectl

  - name: Start and enable Docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Add ubuntu user to the Docker group
    user:
      name: ubuntu
      append: yes
      groups: docker

  - name: Configure containerd
    shell: |
      sudo mkdir -p /etc/containerd
      sudo containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
      sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

  - name: Restart and enable containerd service
    service:
      name: containerd
      state: restarted
      enabled: yes

  - name: Pull Kubernetes control plane images
    shell: kubeadm config images pull

- hosts: role_master
  become: true
  tasks:

  - name: Initialize the Kubernetes cluster using kubeadm
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=All

  - name: Set up kubeconfig for ubuntu user
    shell: |
      mkdir -p /home/ubuntu/.kube
      cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
      chown ubuntu:ubuntu /home/ubuntu/.kube/config

  - name: Apply Flannel network configuration as ubuntu user
    shell: sudo su - ubuntu -c 'kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml'

  - name: Generate join command
    shell: kubeadm token create --print-join-command
    register: join_command_for_workers

  - debug: msg='{{ join_command_for_workers.stdout.strip() }}'

  - name: Register join command for workers
    add_host:
      name: "kube_master"
      worker_join: "{{ join_command_for_workers.stdout.strip() }}"

  - name: Install Helm
    shell: |
      cd /home/ubuntu
      curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      chmod 777 get_helm.sh
      ./get_helm.sh

- hosts: role_worker
  become: true
  tasks:

  - name: Join workers to cluster
    shell: "{{ hostvars['kube_master']['worker_join'] }}"
    register: result_of_joining

  - debug: msg='{{ result_of_joining.stdout }}'
