---
- hosts: all
  become: true
  tasks:
    - name: Change hostnames
      hostname:
        name: "{{ hostvars[inventory_hostname]['private_dns_name'] }}"

    - name: Disable swap
      ansible.posix.mount:
        name: swap
        fstype: swap
        state: absent

    - name: Enable bridged traffic
      sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
        reload: yes
      loop:
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - curl
          - ca-certificates
          - kubelet
          - kubeadm
          - kubectl
          - kubernetes-cni
          - docker.io
        state: present
        update_cache: yes

    - name: Add Kubernetes repository key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /
        state: present
        filename: kubernetes

    - name: Hold Kubernetes packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Configure Docker cgroup driver
      copy:
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"]
          }
        dest: /etc/docker/daemon.json
        mode: '0644'

    - name: Restart and enable Docker
      systemd:
        name: docker
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Configure containerd
      shell: |
        containerd config default | tee /etc/containerd/config.toml
        sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

    - name: Restart and enable containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
        daemon_reload: yes

- hosts: role_master
  become: true
  tasks:
    - name: Pull Kubernetes images
      command: kubeadm config images pull

    - name: Initialize Kubernetes cluster
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=All
      register: kubeadm_init

    - name: Setup kubeconfig for ubuntu user
      become_user: ubuntu
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf to user's kubeconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Install flannel pod network
      become_user: ubuntu
      command: kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Set join command fact
      set_fact:
        worker_join: "{{ join_command.stdout_lines[0] }}"

    - name: Share join command
      set_fact:
        worker_join: "{{ worker_join }}"
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['role_worker'] }}"

- hosts: role_worker
  become: true
  tasks:
    - name: Join workers to cluster
      command: "{{ worker_join }}"
      register: worker_join_result
      until: worker_join_result.rc == 0
      retries: 5
      delay: 30